### ISSUE TITLE
COMPILING NEWTONELIB with IDE 1.8.19 and ARDUINO DUE

### ISSUE THREAD

**Issue by paolovr70** [YordanYordanovGIT/NewToneLib#1]
Hi, compiling my code with NEWTONELIBRARY inside the compiler says this:

C:\Arduino\libraries\NewToneLib-master\NewToneLib.cpp: In member function 'void MyTone::tone(int, int, long unsigned int)':
C:\Arduino\libraries\NewToneLib-master\NewToneLib.cpp:19:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (2 * halfT > duration)
                     ^

Could you fix the bug in the library?
thanks.
paolo

**Comment by thr33bricks** [comment]
Fixed. Thank you for the feedback.
